# -*- coding: utf-8 -*-
"""458webapp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Fr3fowkbbM6W58ofjWxrr2uyYBSi4qS
"""

import pickle

# Load the model
with open('random_forest_model2.pkl', 'rb') as model_file:
    model = pickle.load(model_file)

import pickle
import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestRegressor  # Import the RandomForestRegressor

# Load the model
with open('random_forest_model2.pkl', 'rb') as model_file:
    model = pickle.load(model_file)

# Check the type of the loaded object
print(type(model))  # Print the type of the loaded object

def main():
    st.title("Salary Prediction App")

    # Collect user input
    q11 = st.slider("Q11", 0, 100, 50)
    q30 = st.slider("Q30", 0, 100, 50)
    q27 = st.slider("Q27", 0, 100, 50)
    q26 = st.slider("Q26", 0, 100, 50)
    q23 = st.slider("Q23", 0, 100, 50)

    # Create a DataFrame with user input
    input_data = pd.DataFrame({
        'Q11': [q11],
        'Q30': [q30],
        'Q27': [q27],
        'Q26': [q26],
        'Q23': [q23]
    })

    # Make predictions
    if isinstance(model, RandomForestRegressor):  # Check if the loaded object is a RandomForestRegressor
        prediction = model.predict(input_data)
        st.subheader("Prediction:")
        st.write(f"The predicted salary is: {prediction[0]:.2f}")
    else:
        st.write("Error: The loaded model is not a RandomForestRegressor.")

if __name__ == '__main__':
    main()